const sheetUrl = "https://api.sheetbest.com/sheets/6370568b-e4ec-43f3-b14d-13875e2b5bfe";

// ---------------- Registration ----------------
document.getElementById('registerForm')?.addEventListener('submit', async e=>{
  e.preventDefault();
  const name = document.getElementById('name').value.trim();
  const skill = document.getElementById('skill').value.trim();
  const phone = document.getElementById('phone').value.trim();
  const location = document.getElementById('location').value.trim();
  const msg = document.getElementById('message');

  if(!/^\d{10}$/.test(phone)){
    msg.innerText="Phone must be exactly 10 digits";
    msg.style.color="red";
    return;
  }

  const data={NAME:name,SKILL:skill,PHONE:phone,LOCATION:location};

  try{
    const res = await fetch(sheetUrl,{
      method:'POST',
      headers:{'Content-Type':'application/json'},
      body:JSON.stringify(data)
    });
    if(!res.ok) throw new Error("Sheet error");

    // Save profile to localStorage BEFORE redirect
    localStorage.setItem("profile", JSON.stringify(data));
    msg.innerText="Registration successful!";
    msg.style.color="green";
    setTimeout(()=>window.location.href="profile.html",500);
  }catch(err){
    console.error(err);
    msg.innerText="Registration failed!";
    msg.style.color="red";
  }
});

// ---------------- Profile Page ----------------
document.addEventListener('DOMContentLoaded',()=>{
  const profile = JSON.parse(localStorage.getItem('profile'));
  const container = document.getElementById('profileContainer');

  if(!profile){
    alert("No profile found. Please register first.");
    window.location.href="register.html";
    return;
  }

  container.innerHTML=`
    <p><strong>Name:</strong> ${profile.NAME}</p>
    <p><strong>Skill:</strong> ${profile.SKILL}</p>
    <p><strong>Phone:</strong> ${profile.PHONE}</p>
    <p><strong>Location:</strong> ${profile.LOCATION}</p>
    <div id="qrcode"></div>
    <button id="downloadPDF" class="btn">Download PDF</button>
    <button id="deleteProfile" class="btn danger">Delete Profile</button>
  `;

  // Generate QR code
  new QRCode(document.getElementById("qrcode"),{
    text:`Name:${profile.NAME}\nSkill:${profile.SKILL}\nPhone:${profile.PHONE}\nLocation:${profile.LOCATION}`,
    width:150,height:150
  });

  // ---------------- PDF Download ----------------
  document.getElementById('downloadPDF').addEventListener('click',()=>{
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();

    const logo = new Image();
    logo.src='Unitypass.jpg';

    logo.onload = ()=>{
      // Header background
      doc.setFillColor(255, 140, 0); // orange
      doc.rect(0,0,210,30,'F');

      // Logo
      doc.addImage(logo,'JPEG',10,5,40,20);

      // Title
      doc.setFontSize(18);
      doc.setTextColor(255,255,255);
      doc.setFont('helvetica','bold');
      doc.text("UnityPass Profile",60,20);

      // Profile box with border
      doc.setDrawColor(255,140,0);
      doc.setLineWidth(0.8);
      doc.rect(10,40,190,80);

      // Profile text inside box
      doc.setFontSize(12);
      doc.setTextColor(0,0,0);
      doc.setFont('helvetica','normal');
      doc.text(`Name: ${profile.NAME}`,20,55);
      doc.text(`Skill: ${profile.SKILL}`,20,65);
      doc.text(`Phone: ${profile.PHONE}`,20,75);
      doc.text(`Location: ${profile.LOCATION}`,20,85);

      // QR Code
      const qrCanvas = document.querySelector('#qrcode canvas');
      doc.addImage(qrCanvas.toDataURL('image/png'),'PNG',150,50,50,50);

      // Footer
      doc.setFontSize(10);
      doc.setTextColor(100,100,100);
      doc.text("Generated by UnityPass",10,135);

      doc.save(`${profile.NAME}_UnityPass.pdf`);
    };
  });

  // ---------------- Delete Profile ----------------
  document.getElementById('deleteProfile').addEventListener('click',()=>{
    if(confirm("Are you sure you want to delete your profile?")){
      localStorage.removeItem('profile');
      window.location.href="index.html";
    }
  });
});